site_name: Lakekeeper Docs
repo_url: https://github.com/lakekeeper/lakekeeper
site_description: Lakekeeper is a rust native Iceberg REST Catalog
site_author: Lakekeeper Team
edit_uri: blob/main/docs/

theme:
  custom_dir: overrides
  name: material
  palette:
    scheme: lakekeeper
  logo: assets/bear.svg
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - bash
    - json
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - offline
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Docs:
      - nightly: "!include docs/docs/nightly/mkdocs.yml"
      - latest: "!include docs/docs/latest/mkdocs.yml"
      - Release 0.8.x: "!include docs/docs/0.8.x/mkdocs.yml"
      - Release 0.7.x: "!include docs/docs/0.7.x/mkdocs.yml"
      - Release 0.6.x: "!include docs/docs/0.6.x/mkdocs.yml"
      - Release 0.5.x: "!include docs/docs/0.5.x/mkdocs.yml"
  - Community: support.md
  - About:
      - Release Notes: about/release-notes.md
      - License: about/license.md
      - Code of Conduct: about/code-of-conduct.md
      - Logos: about/logos.md
  - Learn: /#learn

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - markdown_grid_tables
  - pymdownx.snippets:
      # check_paths: True
      restrict_base_path: False
      base_path: .
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2025 <a href="https://lakekeeper.io">Lakekeeper</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Lakekeeper Team</a>.

plugins:
  - monorepo
  - search
  - exclude-search:
      exclude:
        - docs/0.8.x/*
        - docs/0.7.x/*
        - docs/0.6.x/*
        - docs/0.5.x/*
        - docs/nightly/*
  - autorefs

watch:
  - docs
  - overrides

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jkAGG8p93B
    - icon: fontawesome/brands/github
      link: https://github.com/lakekeeper/lakekeeper

extra_css:
  - /assets/css/home.css
  - /assets/css/bootstrap.min.css
  - /assets/css/animate.css
  - /assets/css/odometer.css
  - /assets/css/fontawesome.min.css
  - /assets/css/header.css

extra_javascript:
  - /assets/js/jquery-3.6.0.min.js
  - /assets/js/main.js
  - /assets/js/odometer.js
  - /assets/js/wow.min.js
