[profile.default]
default-filter = """
    not (package(lakekeeper-io) and binary(integration_tests))
    and not test(::aws_integration_tests::)
    and not test(::aws_kms_integration_tests::)
    and not test(::azure_integration_tests::)
    and not test(::azure_system_credentials_integration_tests::)
    and not test(::gcs_integration_tests::)
    and not test(::gcs_hns_integration_tests::)
    and not test(::gcp_system_credentials_integration_tests::)
    and not test(::kv2_integration_tests::)
    and not test(::minio_integration_tests::)
    and not test(::openfga_integration_tests::)
    and not test(::r2_integration_tests::)
"""

[profile.debug]
default-filter = "test(::gcp_system_credentials_integration_tests::)"

[profile.ci]
default-filter = "all()"
failure-output = "immediate-final"
fail-fast = false
retries = 0


[profile.ci.junit] # this can be some other profile, too
path = "junit.xml"
