name: integration tests

on:
  push:
    branches:
      - main
      - 'manual-release-*'
  pull_request:
    branches:
      - main
      - 'manual-release-*'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/docker_build.yml
    with:
      platform: 'amd64'
      dockerfile: 'docker/full.Dockerfile'
      image_name: 'lakekeeper-local'
  tests:
    needs: docker
    strategy:
      fail-fast: false
      matrix:
        names:
          - pyiceberg
          - starrocks
          - trino
          - trino_opa
          - spark_openfga-1.5.2
          - spark_openfga-1.6.1
          - spark_openfga-1.7.1
          - spark_openfga-1.8.0
          - spark_kv2-1.7.1
          - spark_adls-1.5.2
          - spark_adls-1.6.1
          - spark_adls-1.8.0
          - spark_wasbs-1.8.1
          # - spark_adls-1.7.1 adls is currently broken with 1.7.1 due to https://lists.apache.org/thread/xc0ddyjkwdl8rhp072fcydl4rondogx6
          - spark_aws_remote_signing-1.5.2
          - spark_aws_remote_signing-1.6.1
          - spark_aws_remote_signing-1.7.1
          - spark_aws_remote_signing-1.8.0
          - spark_aws_sts-1.5.2
          - spark_aws_sts-1.6.1
          - spark_aws_sts-1.7.1
          - spark_aws_sts-1.8.0
          - spark_gcs-1.5.2
          - spark_gcs-1.6.1
          - spark_gcs-1.7.1
          - spark_gcs-1.8.0
          - spark_minio_sts-1.5.2
          - spark_minio_sts-1.6.1
          - spark_minio_sts-1.7.1
          - spark_minio_sts-1.8.0
          - spark_minio_remote_signing-1.5.2
          - spark_minio_remote_signing-1.6.1
          - spark_minio_remote_signing-1.7.1
          - spark_minio_remote_signing-1.8.0
          - spark_minio_s3a-1.7.1
          - spark_aws_system_identity_sts-1.8.0
          - spark_aws_system_identity_remote_signing-1.8.0
    uses: ./.github/workflows/integration_test_workflow.yml
    with:
        test_name: ${{ matrix.names }}
    secrets: inherit
  integration_tests_results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Integration tests results
    needs: [ tests ]
    steps:
      - run: |
          result="${{ needs.tests.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi